USE recipe;


INSERT INTO categories (name,created,edited) VALUES ('Beef',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Side',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Chicken',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Pork',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Seafood',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Vegetarian',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Dessert',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Lamb',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Miscellaneous',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Pasta',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Vegan',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Breakfast',NOW(),NOW());
INSERT INTO categories (name,created,edited) VALUES ('Starter',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1000, 'Spaghetti Bolognese', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                     'Beef'),
                                                                                                                       'Put the onion and oil in a large pan and fry over a fairly high heat for 3-4 mins. Add the garlic and mince and fry until they both brown. Add the mushrooms and herbs, and cook for another couple of mins.\r\n\r\nStir in the tomatoes, beef stock, tomato ketchup or purée, Worcestershire sauce and seasoning. Bring to the boil, then reduce the heat, cover and simmer, stirring occasionally, for 30 mins.\r\n\r\nMeanwhile, cook the spaghetti in a large pan of boiling, salted water, according to packet instructions. Drain well, run hot water through it, put it back in the pan and add a dash of olive oil, if you like, then stir in the meat sauce. Serve in hot bowls and hand round Parmesan cheese, for sprinkling on top.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg', 'https://www.you_tube.com/watch?v=-gF8d-fitkU',
                                                                                                                       'onions,olive oil,garlic,lean minced beef,mushrooms,dried oregano,tomatoes,hot beef stock,tomato puree,worcestershire sauce,spaghetti,parmesan', '
       null',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1001, 'Mulukhiyah', (SELECT id FROM categories WHERE name =
                                                                                                                                                                            'Beef'),
                                                                                                                       'Saute the onions in the 3-4 tablespoons olive oil\r\nAdd the beef cubes or the chicken cutlets, sear for 3-4 min on each side\r\nAdd 1 liter of water or just enough to cover the meat\r\nCook over medium heat until the meat is done (I usually do this in the pressure cooker and press them for 5 min)\r\n\r\nAdd the frozen mulukhyia and stir until it thaws completely and then comes to a boil\r\n\r\nIn another pan add the 1/4 to 1/2 cup of olive oil and the cloves of garlic and cook over medium low heat until you can smell the garlic (don’t brown it, it will become bitter)\r\n\r\nAdd the oil and garlic to the mulukhyia and lower the heat and simmer for 5-10 minutes\r\nAdd salt to taste\r\n\r\nServe with a generous amount of lemon juice.\r\n\r\nYou can serve it with some short grain rice or some pita bread',
                                                                                                                       'https://www.themealdb.com/images/media/meals/x372ug1598733932.jpg', 'https://www.you_tube.com/watch?v=vWc5JzgAkIQ',
                                                                                                                       'Mulukhiyah,Onion,Beef,Salt,Water,Garlic Clove,Olive Oil', '
       https://chefindisguise.com/2017/05/15/mulukhiyah-a-stew-fit-for-royals/',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1002, 'Pierogi (Polish Dumplings)', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                            'Side'),
                                                                                                                       'To prepare the sauerkraut filling, melt the butter in a skillet over medium heat. Stir in the onion, and cook until translucent, about 5 minutes. Add the drained sauerkraut and cook for an additional 5 minutes. Season to taste with salt and pepper, then remove to a plate to cool.\r\n\r\nFor the mashed potato filling, melt the butter in a skillet over medium heat. Stir in the onion, and cook until translucent, about 5 minutes. Stir into the mashed potatoes, and season with salt and white pepper.\r\n\r\nTo make the dough, beat together the eggs and sour cream until smooth. Sift together the flour, salt, and baking powder; stir into the sour cream mixture until dough comes together. Knead the dough on a lightly floured surface until firm and smooth. Divide the dough in half, then roll out one half to 1/8 inch thickness. Cut into 3 inch rounds using a biscuit cutter.\r\n\r\nPlace a small spoonful of the mashed potato filling into the center of each round. Moisten the edges with water, fold over, and press together with a fork to seal. Repeat procedure with the remaining dough and the sauerkraut filling.\r\n\r\nBring a large pot of lightly salted water to a boil. Add perogies and cook for 3 to 5 minutes or until pierogi float to the top. Remove with a slotted spoon.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/45xxr21593348847.jpg', 'https://www.you_tube.com/watch?v=lyqDmUroZrI',
                                                                                                                       'Butter,Chopped Onion,Sauerkraut,Butter,Chopped Onion,Potatoes,Eggs,Sour Cream,Flour,Salt,Baking Powder', '
       https://www.allrecipes.com/recipe/109914/pierogi-polish-dumplings/',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1003, 'Kung Pao Chicken', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                  'Chicken'),
                                                                                                                       'Combine the sake or rice wine, soy sauce, sesame oil and cornflour dissolved in water. Divide mixture in half.\r\nIn a glass dish or bowl, combine half of the sake mixture with the chicken pieces and toss to coat. Cover dish and place in refrigerator for about 30 minutes.\r\nIn a medium frying pan, combine remaining sake mixture, chillies, vinegar and sugar. Mix together and add spring onion, garlic, water chestnuts and peanuts. Heat sauce slowly over medium heat until aromatic.\r\nMeanwhile, remove chicken from marinade and sauté in a large frying pan until juices run clear. When sauce is aromatic, add sautéed chicken and let simmer together until sauce thickens.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/1525872624.jpg', 'https://www.you_tube.com/watch?v=QqdcCHQlOe0',
                                                                                                                       'Sake,Soy Sauce,Sesame Seed Oil,Corn Flour,Water,Chicken,Chilli Powder,Rice Vinegar,Brown Sugar,Spring Onions,Garlic Clove,Water Chestnut,Peanuts', '
       http://allrecipes.co.uk/recipe/1773/kung-pao-chicken.aspx',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1004, 'Beef Bourguignon', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                  'Beef'),
                                                                                                                       'Heat a large casserole pan and add 1 tbsp goose fat. Season the beef and fry until golden brown, about 3-5 mins, then turn over and fry the other side until the meat is browned all over, adding more fat if necessary. Do this in 2-3 batches, transferring the meat to a colander set over a bowl when browned.\r\nIn the same pan, fry the bacon, shallots or pearl onions, mushrooms, garlic and bouquet garni until lightly browned. Mix in the tomato purée and cook for a few mins, stirring into the mixture. This enriches the bourguignon and makes a great base for the stew. Then return the beef and any drained juices to the pan and stir through.\r\nPour over the wine and about 100ml water so the meat bobs up from the liquid, but isn’t completely covered. Bring to the boil and use a spoon to scrape the caramelised cooking juices from the bottom of the pan – this will give the stew more flavour.\r\nHeat oven to 150C/fan 130C/gas 2. Make a cartouche: tear off a square of foil slightly larger than the casserole, arrange it in the pan so it covers the top of the stew and trim away any excess foil. Then cook for 3 hrs. If the sauce looks watery, remove the beef and veg with a slotted spoon, and set aside. Cook the sauce over a high heat for a few mins until the sauce has thickened a little, then return the beef and vegetables to the pan.\r\nTo make the celeriac mash, peel the celeriac and cut into cubes. Heat the olive oil in a large frying pan. Tip in the celeriac and fry for 5 mins until it turns golden. Season well with salt and pepper. Stir in the rosemary, thyme, bay and cardamom pods, then pour over 200ml water, enough to nearly cover the celeriac. Turn the heat to low, partially cover the pan and leave to simmer for 25-30 mins.\r\nAfter 25-30 mins, the celeriac should be soft and most of the water will have evaporated. Drain away any remaining water, then remove the herb sprigs, bay and cardamom pods. Lightly crush with a potato masher, then finish with a glug of olive oil and season to taste. Spoon the beef bourguignon into serving bowls and place a large spoonful of the celeriac mash on top. Garnish with one of the bay leaves, if you like.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/vtqxtu1511784197.jpg', 'https://www.you_tube.com/watch?v=SQnr4Z-7rok',
                                                                                                                       'Goose Fat,Beef Shin,Bacon,Challots,Chestnut Mushroom,Garlic Clove,Bouquet Garni,Tomato Puree,Red Wine,Celeriac,Olive Oil,Thyme,Rosemary,Bay Leaf,Cardamom', '
       https://www.bbcgoodfood.com/recipes/5032/beef-bourguignon',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1005, 'Chicken Handi', (SELECT id FROM categories WHERE name =
                                                                                                                                                                               'Chicken'),
                                                                                                                       'Take a large pot or wok, big enough to cook all the chicken, and heat the oil in it. Once the oil is hot, add sliced onion and fry them until deep golden brown. Then take them out on a plate and set aside.\r\nTo the same pot, add the chopped garlic and sauté for a minute. Then add the chopped tomatoes and cook until tomatoes turn soft. This would take about 5 minutes.\r\nThen return the fried onion to the pot and stir. Add ginger paste and sauté well.\r\nNow add the cumin seeds, half of the coriander seeds and chopped green chillies. Give them a quick stir.\r\nNext goes in the spices – turmeric powder and red chilli powder. Sauté the spices well for couple of minutes.\r\nAdd the chicken pieces to the wok, season it with salt to taste and cook the chicken covered on medium-low heat until the chicken is almost cooked through. This would take about 15 minutes. Slowly sautéing the chicken will enhance the flavor, so do not expedite this step by putting it on high heat.\r\nWhen the oil separates from the spices, add the beaten yogurt keeping the heat on lowest so that the yogurt doesn’t split. Sprinkle the remaining coriander seeds and add half of the dried fenugreek leaves. Mix well.\r\nFinally add the cream and give a final mix to combine everything well.\r\nSprinkle the remaining kasuri methi and garam masala and serve the chicken handi hot with naan or rotis. Enjoy!',
                                                                                                                       'https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg', 'https://www.you_tube.com/watch?v=IO0issT0Rmc',
                                                                                                                       'Chicken,Onion,Tomatoes,Garlic,Ginger paste,Vegetable oil,Cumin seeds,Coriander seeds,Turmeric powder,Chilli powder,Green chilli,Yogurt,Cream,fenugreek,Garam masala,Salt', '
       ',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1006, 'Toad In The Hole', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                  'Pork'),
                                                                                                                       'Preheat the oven to 200°C/fan180°C/gas 6. fry sausages in a non-stick pan until browned.\r\nDrizzle vegetable oil in a 30cm x 25cm x 6cm deep roasting tray and heat in the oven for 5 minutes.\r\nPut the plain flour in a bowl, crack in the medium free-range eggs, then stir in the grated horseradish. Gradually beat in the semi-skimmed milk. Season.\r\nPut the sausages into the hot roasting tray and pour over the batter. Top with cherry tomatoes on the vine and cook for 30 minutes until puffed and golden.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/ytuvwr1503070420.jpg', 'https://www.you_tube.com/watch?v=t1dWkDrC330',
                                                                                                                       'sausages,vegetable oil,plain flour,eggs,horseradish,milk,cherry tomatoes', '
       http://www.deliciousmagazine.co.uk/recipes/georgina-fuggles-horseradish-and-vine-tomato-toad-in-the-hole/',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1007, 'Escovitch Fish', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                'Seafood'),
                                                                                                                       'Rinse fish; rub with lemon or lime, seasoned with salt and pepper or use your favorite seasoning. I used creole seasoning. Set aside or place in the oven to keep it warm until sauce is ready.\r\n\r\nIn large skillet heat oil over medium heat, until hot, add the fish, cook each side- for about 5-7 minutes until cooked through and crispy on both sides. Remove fish and set aside. Drain oil and leave about 2-3 tablespoons of oil\r\nAdd, bay leave, garlic and ginger, stir-fry for about a minute making sure the garlic does not burn\r\nThen add onion, bell peppers, thyme, scotch bonnet, sugar, all spice-continue stirring for about 2-3 minutes. Add vinegar, mix an adjust salt and pepper according to preference. Let it simmer for about 2 more minutes. \r\n\r\nDiscard bay leave, thyme spring and serve over fish with a side of this bammy. You may make the sauce about 2 days in advance.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/1520084413.jpg', 'https://www.you_tube.com/watch?v=nF6DOtGE6k8',
                                                                                                                       'Red Snapper,Vegetable Oil,Garlic,Ginger,Thyme,Bay Leaf,Red Pepper,Yellow Pepper,Onion,Carrots,Sugar,Allspice,Worcestershire Sauce,Scotch Bonnet,Lime,Malt Vinegar,Pepper', '
       https://www.africanbites.com/jamaican-escovitched-fish/',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1008, 'Red Peas Soup', (SELECT id FROM categories WHERE name =
                                                                                                                                                                               'Beef'),
                                                                                                                       'Wash and rinse the dried kidney beans.. then cover with water in a deep bowl. Remember as they soak they will expand to at least triple the size they were originally so add a lot of water to the bowl. Soak them overnight or for at least 2 hrs to make the cooking step go quicker. I tossed out the water they were soaked in after it did the job.\r\n\r\nHave your butcher cut the salted pigtail into 2 inch pieces as it will be very difficult to cut with an ordinary kitchen knife. Wash, then place a deep pot with water and bring to a boil. Cook for 20 minutes, then drain + rinse and repeat (boil again in water). The goal is to make the pieces of pig tails tender and to remove most of the salt it was cured in.\r\n\r\nTime to start the soup. Place everything in the pot (except the flour and potato), then cover with water and place on a high flame to bring to a boil. As it comes to a boil, skim off any scum/froth at the top and discard. Reduce the heat to a gentle boil and allow it to cook for 1 hr and 15 mins.. basically until the beans are tender and start falling apart.\r\n\r\nIt’s now time to add the potato (and Yams etc if you’re adding it) as well as the coconut milk and continue cooking for 15 minutes.\r\n\r\nNow is a good time to start making the basic dough for the spinner dumplings. Mix the flour and water (add a pinch of salt if you want) until you have a soft/smooth dough. allow it to rest for 5 minutes, then pinch of a tablespoon at a time and roll between your hands to form a cigarette shape.\r\n\r\nAdd them to the pot, stir well and continue cooking for another 15 minutes on a rolling boil.\r\n\r\nYou’ll notice that I didn’t add any salt to the pot as the remaining salt from the salted pigtails will be enough to properly season this dish. However you can taste and adjust accordingly. Lets recap the timing part of things so you’re not confused. Cook the base of the soup for 1 hr and 15 minute or until tender, then add the potatoes and cook for 15 minutes, then add the dumplings and cook for a further 15 minutes. Keep in mind that this soup will thicken quite a bit as it cools.\r\n\r\nWhile this is not a traditional recipe to any one specific island, versions of this soup (sometimes called stewed peas) can be found throughout the Caribbean, Latin America and Africa. A hearty bowl of this soup will surely give you the sleepies (some may call it ethnic fatigue). You can certainly freeze the leftovers and heat it up another day.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/sqpqtp1515365614.jpg', 'https://www.you_tube.com/watch?v=1ogCfDXotMw',
                                                                                                                       'Kidney Beans,Carrots,Spring Onions,Thyme,Onion,Black Pepper,Red Pepper,Garlic Clove,Allspice,Beef,Water,Potatoes,Plain Flour,Water,Coconut Milk', '
       http://caribbeanpot.com/caribbean-red-peas-soup/',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1009, 'Beef Caldereta', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                'Beef'),
                                                                                                                       '0.	Heat oil in a cooking pot. Saute onion and garlic until onion softens\r\n1.	Add beef. Saute until the outer part turns light brown.\r\n2.	Add soy sauce. Pour tomato sauce and water. Let boil.\r\n3.	Add Knorr Beef Cube. Cover the pressure cooker. Cook for 30 minutes.\r\n4.	Pan-fry carrot and potato until it browns. Set aside.\r\n5.	Add chili pepper, liver spread and peanut butter. Stir.\r\n6.	Add bell peppers, fried potato and carrot. Cover the pot. Continue cooking for 5 to 7 minutes.\r\n7.	Season with salt and ground black pepper. Serve.\r\n',
                                                                                                                       'https://www.themealdb.com/images/media/meals/41cxjh1683207682.jpg', 'https://www.you_tube.com/watch?v=yI7hTz0ft5k',
                                                                                                                       'Beef,Beef Stock,Soy Sauce,Water,Green Pepper,Red Pepper,Potatoes,Carrots,Tomato Puree,Peanut Butter,Chilli Powder,Onion,Garlic,Olive Oil', '
       https://www.kawalingpinoy.com/beef-caldereta/',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1010, 'Shakshuka', (SELECT id FROM categories WHERE name =
                                                                                                                                                                           'Vegetarian'),
                                                                                                                       'Heat the oil in a frying pan that has a lid, then soften the onions, chilli, garlic and coriander stalks for 5 mins until soft. Stir in the tomatoes and sugar, then bubble for 8-10 mins until thick. Can be frozen for 1 month.\r\n\r\nUsing the back of a large spoon, make 4 dips in the sauce, then crack an egg into each one. Put a lid on the pan, then cook over a low heat for 6-8 mins, until the eggs are done to your liking. Scatter with the coriander leaves and serve with crusty bread.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/g373701551450225.jpg', 'https://www.you_tube.com/watch?v=C-3_jYrfdBU',
                                                                                                                       'Olive Oil,Red Onions,Red Chilli,Garlic,Coriander,Cherry Tomatoes,Caster Sugar,Eggs,Feta', '
       https://www.bbcgoodfood.com/recipes/7573/spicy-tomato-baked-eggs',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1011, 'Brie wrapped in prosciutto & brioche', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                                      'Side'),
                                                                                                                       'Mix the flour, 1 tsp salt, caster sugar, yeast, milk and eggs together in a mixer using the dough attachment for 5 mins until the dough is smooth. Add the butter and mix for a further 4 mins on medium speed. Scrape the dough bowl and mix again for 1 min. Place the dough in a container, cover with cling film and leave in the fridge for at least 6 hrs before using.\r\nWrap the Brie in the prosciutto and set aside. Turn out the dough onto a lightly floured surface. Roll into a 25cm circle. Place the wrapped Brie in the middle of the circle and fold the edges in neatly. Put the parcel onto a baking tray lined with baking parchment and brush with beaten egg. Chill in the fridge for 30 mins, then brush again with beaten egg and chill for a further 30 mins. Leave to rise for 1 hr at room temperature. Heat oven to 200C/180C fan/gas 6, then bake for 22 mins. Serve warm.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/qqpwsy1511796276.jpg', 'https://www.you_tube.com/watch?v=FzNPPD8lbWg',
                                                                                                                       'Plain Flour,Caster Sugar,Yeast,Milk,Eggs,Eggs,Butter,Brie,Prosciutto', '
       https://www.bbcgoodfood.com/recipes/1803634/brie-wrapped-in-prosciutto-and-brioche',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1012, 'Bitterballen (Dutch meatballs)', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                                'Beef'),
                                                                                                                       'Melt the butter in a skillet or pan. When melted, add the flour little by little and stir into a thick paste. Slowly stir in the stock, making sure the roux absorbs the liquid. Simmer for a couple of minutes on a low heat while you stir in the onion, parsley and the shredded meat. The mixture should thicken and turn into a heavy, thick sauce.\r\n\r\nPour the mixture into a shallow container, cover and refrigerate for several hours, or until the sauce has solidified.\r\n\r\nTake a heaping tablespoon of the cold, thick sauce and quickly roll it into a small ball. Roll lightly through the flour, then the egg and finally the breadcrumbs. Make sure that the egg covers the whole surface of the bitterbal. When done, refrigerate the snacks while the oil in your fryer heats up to 190C (375F). Fry four bitterballen at a time, until golden.\r\n\r\nServe on a plate with a nice grainy or spicy mustard. \r\n',
                                                                                                                       'https://www.themealdb.com/images/media/meals/lhqev81565090111.jpg', 'https://www.you_tube.com/watch?v=q8AKfYUtDuM',
                                                                                                                       'Butter,Flour,Beef Stock,Onion,Parsley,Beef,Salt,Pepper,Nutmeg,Flour,Eggs,Breadcrumbs', '
       https://www.holland.com/global/tourism/information/traditional-dutch-food/bitterballen.htm',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1013, 'Baingan Bharta', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                'Vegetarian'),
                                                                                                                       'Rinse the baingan (eggplant or aubergine) in water. Pat dry with a kitchen napkin. Apply some oil all over and\r\nkeep it for roasting on an open flame. You can also grill the baingan or roast in the oven. But then you won\'t get\r\nthe smoky flavor of the baingan. Keep the eggplant turning after a 2 to 3 minutes on the flame, so that its evenly\r\ncooked. You could also embed some garlic cloves in the baingan and then roast it.\r\n2. Roast the aubergine till its completely cooked and tender. With a knife check the doneness. The knife should slid\r\neasily in aubergines without any resistance. Remove the baingan and immerse in a bowl of water till it cools\r\ndown.\r\n3. You can also do the dhungar technique of infusing charcoal smoky flavor in the baingan. This is an optional step.\r\nUse natural charcoal for this method. Heat a small piece of charcoal on flame till it becomes smoking hot and red.\r\n4. Make small cuts on the baingan with a knife. Place the red hot charcoal in the same plate where the roasted\r\naubergine is kept. Add a few drops of oil on the charcoal. The charcoal would begin to smoke.\r\n5. As soon as smoke begins to release from the charcoal, cover the entire plate tightly with a large bowl. Allow the\r\ncharcoal smoke to get infused for 1 to 2 minutes. The more you do, the more smoky the baingan bharta will\r\nbecome. I just keep for a minute. Alternatively, you can also do this dhungar method once the baingan bharta is\r\ncooked, just like the way we do for Dal Tadka.\r\n6. Peel the skin from the roasted and smoked eggplant.\r\n7. Chop the cooked eggplant finely or you can even mash it.\r\n8. In a kadai or pan, heat oil. Then add finely chopped onions and garlic.\r\n9. Saute the onions till translucent. Don\'t brown them.\r\n10. Add chopped green chilies and saute for a minute.\r\n11. Add the chopped tomatoes and mix it well.\r\n12. Bhuno (saute) the tomatoes till the oil starts separating from the mixture.\r\n13. Now add the red chili powder. Stir and mix well.\r\n14. Add the chopped cooked baingan.\r\n15. Stir and mix the chopped baingan very well with the onion­tomato masala mixture.\r\n16. Season with salt. Stir and saute for some more 4 to 5 minutes more.\r\n17. Finally stir in the coriander leaves with the baingan bharta or garnish it with them. Serve Baingan Bharta with\r\nphulkas, rotis or chapatis. It goes well even with bread, toasted or grilled bread and plain rice or jeera rice.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg', 'https://www.you_tube.com/watch?v=-84Zz2EP4h4',
                                                                                                                       'Aubergine,Onion,Tomatoes,Garlic,Green Chili,Red Chili Powder,Oil,Coriander Leaves,salt', '
       http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1014, 'Honey Teriyaki Salmon', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                       'Seafood'),
                                                                                                                       'Mix all the ingredients in the Honey Teriyaki Glaze together. Whisk to blend well. Combine the salmon and the Glaze together.\r\n\r\nHeat up a skillet on medium-low heat. Add the oil, Pan-fry the salmon on both sides until it’s completely cooked inside and the glaze thickens.\r\n\r\nGarnish with sesame and serve immediately.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg', 'https://www.you_tube.com/watch?v=4MpYuaJsvRw',
                                                                                                                       'Salmon,Olive oil,Soy Sauce,Sake,Sesame Seed', '
       null',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1015, 'Seri muka kuih', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                'Dessert'),
                                                                                                                       'Soak glutinous rice with water for at least 1 ½ hours prior to using. Drain.\r\nPrepare a 9-inch round or square cake pan and spray with cooking spray or line with plastic wrap.\r\nMix coconut milk, water, salt and the rice. Pour it into cake pan, topped with the pandan knots.\r\nSteam for 30 minutes.\r\nAfter 30 minutes, fluff up the rice and remove pandan knots. Then, using a greased spatula, flatten the steamed rice. Make sure there are no holes/air bubbles and gaps in the rice, especially the sides.\r\nSteam for another 10 minutes.\r\n\r\nCombine pandan juice, coconut milk, all purpose flour, cornflour, and sugar. Mix well.\r\nAdd eggs and whisk well then strain into a medium sized metal bowl or pot.\r\nPlace pandan mixture over simmering water (double boiler or bain-marie)\r\nStir continuously and cook till custard starts to thicken. (15 minutes)\r\nPour pandan custard into glutinous rice layer, give it a little tap (for air bubbles) and continue to steam for 30 minutes.\r\nRemove kuih seri muka from the steamer and allow to cool completely before cutting into rectangles or diamond shapes.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/6ut2og1619790195.jpg', 'https://www.you_tube.com/watch?v=_NJtCfqgaBo',
                                                                                                                       'Rice,Coconut Milk,Water,Salt,Corn Flour,Flour,Eggs,Coconut Cream,Sugar', '
       https://makan.ch/recipe/kuih-seri-muka/',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1016, 'Salted Caramel Cheescake', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                          'Dessert'),
                                                                                                                       '1) Blitz the biscuits and the pretzels in a food processor and mix the biscuits with the melted butter. Spread on the bottom of an 8″/20cm Deep Springform Tin and press down firmly. Leave to set in the fridge whilst you make the rest!\r\n\r\n2) Using an electric mixer, I use my KitchenAid with the whisk attachment, whisk together the cream cheese, vanilla, and icing sugar until smooth and then add the caramel and whisk again until smooth and lump free – this could take a couple of minutes, I whisk it at half speed so not too quick or slow!\r\n\r\n3) Pour in the double cream & Salt flakes and continue to whisk for a couple of minutes until its very thick and mousse like (I mix it on a medium speed, level 6/10) – Now this could take up to 5 minutes depending on your mixer, but you seriously have to stick at it – it will hold itself completely when finished mixing (like a meringue does!) If you don’t mix it enough it will not set well enough, but don’t get impatient and whisk it really quick because that’ll make it split! Spread over the biscuit base and leave to set in the fridge overnight.\r\n\r\n4) Remove the Cheesecake from the tin carefully and decorate the cheesecake – I drizzled over some of the spare caramel, and then some Toffee Popcorn and more Pretzels!',
                                                                                                                       'https://www.themealdb.com/images/media/meals/xqrwyr1511133646.jpg', 'https://www.you_tube.com/watch?v=q5dQp3qpmI4',
                                                                                                                       'Digestive Biscuits,Pretzels,Butter,Cream Cheese,Vanilla Extract,Icing Sugar,Caramel,Sea Salt,Double Cream,Caramel Sauce,Toffee Popcorn,Pretzels', '
       http://www.janespatisserie.com/2015/11/09/no-bake-salted-caramel-cheesecake/',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1017, 'Skillet Apple Pork Chops with Roasted Sweet Potatoes & Zucchini', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                                                                 'Pork'),
                                                                                                                       '\r\nServes 2\r\n\r\n\r\n1. \r\n\r\nAdjust racks to top and middle positions and preheat oven to 450 degrees. Wash and dry all produce. Dice sweet potatoes into 1/2-inch pieces. Toss on a baking sheet with a drizzle of oil, salt, and pepper. Roast on top rack for 12 minutes (we\'ll roast the zucchini then). \r\n\r\n\r\n2. \r\n\r\nMeanwhile, halve and core apple; thinly slice into half-moons. Peel and finely chop garlic. Quarter lemon. Trim and halve zucchini lengthwise; cut crosswise into 1/2-inch-thick half-moons. Toss on a second baking sheet with a drizzle of oil and a pinch of salt and pepper. Set aside. \r\n\r\n\r\n3. \r\n\r\nPat pork dry with paper towels and season all over with salt and pepper. Heat a drizzle of oil in a large pan over medium-high heat. Add pork and cook until browned and cooked through, 4-5 minutes per side. Turn off heat; transfer to a plate. \r\n\r\n\r\n4. \r\n\r\nOnce sweet potatoes have roasted 12 minutes, transfer baking sheet with zucchini to middle rack and continue roasting until both veggies are browned and softened, 12-15 minutes more. \r\n\r\n\r\n5. \r\n\r\nMeanwhile, melt 1 TBSP butter (2 TBSP for 4 servings) in pan used for pork over medium-high heat. Add apple and season with salt and pepper. Cook, scraping up any browned bits from bottom of pan, until apple is slightly softened, 2-3 minutes. Add garlic; cook until fragrant, 30 seconds. Add 1/z cup water (3/4 cup for 4), stock concentrate, and 11/2 tsp sugar (3 tsp for 4). Cook, stirring, until sauce has thickened and apple is very tender, 3-5 minutes. Season with salt and pepper. \r\n\r\n\r\n6. \r\n\r\nRemove pan with apple from heat; stir in 1 TBSP butter (2 TBSP for 4 servings) and a squeeze of lemon juice. Divide pork, zucchini, and sweet potatoes between plates. Top pork with glazed apple sauce. Top zucchini with a squeeze of lemon juice. ',
      'https://www.themealdb.com/images/media/meals/h3ijwo1581013377.jpg', '',
      'Potatoes,Apples,Garlic,Lemon,Pork,Zucchini,Chicken Stock,Vegetable Oil,Sugar,Butter', '
       ',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1018, 'Croatian Bean Stew', (SELECT id FROM categories WHERE name =
                                                                                                                                                                     'Beef'),
                                                                                                        'Heat the oil in a pan. Add the chopped vegetables and sauté until tender. Take a pot, empty the beans together with the vegetables into it, put the sausages inside and cook for further 20 minutes on a low heat. Or, put it in an oven and bake it at a temperature of 180ºC/350ºF for 30 minutes. This dish is even better reheated the next day.',
                                                                                                        'https://www.themealdb.com/images/media/meals/tnwy8m1628770384.jpg', 'https://www.you_tube.com/watch?v=mrjnQal3S1A',
                                                                                                        'Cannellini Beans,Vegetable Oil,Tomatoes,Challots,Garlic,Parsley,Chorizo', '
       https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1019, 'Teriyaki Chicken Casserole', (SELECT id FROM categories WHERE name =
                                                                                                                                                                             'Chicken'),
                                                                                                        'Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!',
                                                                                                        'https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg', 'https://www.you_tube.com/watch?v=4aZr5hZXP_s',
                                                                                                        'soy sauce,water,brown sugar,ground ginger,minced garlic,cornstarch,chicken breasts,stir-fry vegetables,brown rice', '
       null',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1020, 'Pierogi (Polish Dumplings)', (SELECT id FROM categories WHERE name =
                                                                                                                                                                             'Side'),
                                                                                                        'To prepare the sauerkraut filling, melt the butter in a skillet over medium heat. Stir in the onion, and cook until translucent, about 5 minutes. Add the drained sauerkraut and cook for an additional 5 minutes. Season to taste with salt and pepper, then remove to a plate to cool.\r\n\r\nFor the mashed potato filling, melt the butter in a skillet over medium heat. Stir in the onion, and cook until translucent, about 5 minutes. Stir into the mashed potatoes, and season with salt and white pepper.\r\n\r\nTo make the dough, beat together the eggs and sour cream until smooth. Sift together the flour, salt, and baking powder; stir into the sour cream mixture until dough comes together. Knead the dough on a lightly floured surface until firm and smooth. Divide the dough in half, then roll out one half to 1/8 inch thickness. Cut into 3 inch rounds using a biscuit cutter.\r\n\r\nPlace a small spoonful of the mashed potato filling into the center of each round. Moisten the edges with water, fold over, and press together with a fork to seal. Repeat procedure with the remaining dough and the sauerkraut filling.\r\n\r\nBring a large pot of lightly salted water to a boil. Add perogies and cook for 3 to 5 minutes or until pierogi float to the top. Remove with a slotted spoon.',
                                                                                                        'https://www.themealdb.com/images/media/meals/45xxr21593348847.jpg', 'https://www.you_tube.com/watch?v=lyqDmUroZrI',
                                                                                                        'Butter,Chopped Onion,Sauerkraut,Butter,Chopped Onion,Potatoes,Eggs,Sour Cream,Flour,Salt,Baking Powder', '
       https://www.allrecipes.com/recipe/109914/pierogi-polish-dumplings/',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1021, 'Lamb tomato and sweet spices', (SELECT id FROM categories WHERE name =
                                                                                                                                                                               'Lamb'),
                                                                                                        'Use pickled vine leaves here, preserved in brine. Small delicate leaves are better than the large bristly ones but, if only large leaves are to hand, then trim them to roughly 12 by 12 cms so that you don\'t get too many layers of leaves around the filling. And remove any stalks. Drain the preserved leaves, immerse them in boiling water for 10 minutes and then leave to dry on a tea towel before use. \r\nBasmati rice with butter and pine nuts is an ideal accompaniment. Couscous is great, too. Serves four.\r\nFirst make the filling. Put all the ingredients, apart from the tomatoes, in a bowl. Cut the tomatoes in half, coarsely grate into the bowl and discard the skins. Add half a teaspoon of salt and some black pepper, and stir. Leave on the side, or in the fridge, for up to a day. Before using, gently squeeze with your hands and drain away any juices that come out.\r\nTo make the sauce, heat the oil in a medium pan. Add the ginger and garlic, cook for a minute or two, taking care not to burn them, then add the tomato, lemon juice and sugar. Season, and simmer for 20 minutes.\r\nWhile the sauce is bubbling away, prepare the vine leaves. Use any torn or broken leaves to line the base of a wide, heavy saucepan. Trim any leaves from the fennel, cut it vertically into 0.5cm-thick slices and spread over the base of the pan to cover completely.\r\nLay a prepared vine leaf (see intro) on a work surface, veiny side up. Put two teaspoons of filling at the base of the leaf in a 2cm-long by 1cm-wide strip. Fold the sides of the leaf over the filling, then roll it tightly from bottom to top, in a cigar shape. Place in the pan, seam down, and repeat with the remaining leaves, placing them tightly next to each other in lines or circles (in two layers if necessary).\r\nPour the sauce over the leaves (and, if needed, add water just to cover). Place a plate on top, to weigh the leaves down, then cover with a lid. Bring to a boil, reduce the heat and cook on a bare simmer for 70 minutes. Most of the liquid should evaporate. Remove from the heat, and leave to cool a little - they are best served warm. When serving, bring to the table in the pan - it looks great. Serve a few vine leaves and fennel slices with warm rice. Spoon the braising juices on top and garnish with coriander.',
      'https://www.themealdb.com/images/media/meals/qtwtss1468572261.jpg', 'https://www.you_tube.com/watch?v=vaZb1MnFBgA',
      'olive oil,ginger,garlic,tomatoes,lemon juice,caster sugar,vine leaves,fennel bulb,lamb mince,onion,potato,basmati rice,chopped parsley,coriander,lemon juice,garlic,clove,cinnamon,tomatoes', '
       http://www.ottolenghi.co.uk/recipes/meat/lamb-tomato-and-sweet-spices-shop',NOW(),NOW());
INSERT INTO recipes (id, name, category_id, instructions, thumb, you_tube, ingredients, source,created,edited) VALUES (1022, 'French Omelette', (SELECT id FROM categories WHERE name =
                                                                                                                                                                                 'Miscellaneous'),
                                                                                                                       'Get everything ready. Warm a 20cm (measured across the top) non-stick frying pan on a medium heat. Crack the eggs into a bowl and beat them with a fork so they break up and mix, but not as completely as you would for scrambled egg. With the heat on medium-hot, drop one knob of butter into the pan. It should bubble and sizzle, but not brown. Season the eggs with the Parmesan and a little salt and pepper, and pour into the pan.\r\nLet the eggs bubble slightly for a couple of seconds, then take a wooden fork or spatula and gently draw the mixture in from the sides of the pan a few times, so it gathers in folds in the centre. Leave for a few seconds, then stir again to lightly combine uncooked egg with cooked. Leave briefly again, and when partly cooked, stir a bit faster, stopping while there’s some barely cooked egg left. With the pan flat on the heat, shake it back and forth a few times to settle the mixture. It should slide easily in the pan and look soft and moist on top. A quick burst of heat will brown the underside.\r\nGrip the handle underneath. Tilt the pan down away from you and let the omelette fall to the edge. Fold the side nearest to you over by a third with your fork, and keep it rolling over, so the omelette tips onto a plate – or fold it in half, if that’s easier. For a neat finish, cover the omelette with a piece of kitchen paper and plump it up a bit with your fingers. Rub the other knob of butter over to glaze. Serve immediately.',
                                                                                                                       'https://www.themealdb.com/images/media/meals/yvpuuy1511797244.jpg', 'https://www.you_tube.com/watch?v=qXPhVYpQLPA',
                                                                                                                       'Eggs,Butter,Parmesan,Tarragon,Parsley,Chives,Gruyère', '
       https://www.bbcgoodfood.com/recipes/1669/ultimate-french-omelette',NOW(),NOW());